services:
  - type: web
    name: django-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Spotify_recommend_sys.wsgi:application 
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
